---
title: "R Notebook"
output: html_notebook
---
## MYSQL on Aiven
```{r}
# 1. install lib
install.packages("RMySQL")
install.packages("DBI")
```


```{r, echo = FALSE, message=FALSE, results='hide'}
# 2. settings
library(DBI)
library(RMySQL)

# Connect to Database
db_path1 <- "music-sales.db"
conn <- dbConnect(RSQLite::SQLite(), dbname = db_path1)
print("music sales db connection succeeded!")

db_path2 <- "film-sales.db"
con <- dbConnect(RSQLite::SQLite(), dbname = db_path1)
print("film sales db connection succeeded!")
```


```{r, echo = FALSE, message=FALSE, results='hide'}
# Show all tables in the database
dbListTables(conn)
dbListTables(con)

```


```{r, echo = FALSE, message=FALSE, results='hide'}
# 2. settings
db_user <- 'avnadmin'
db_password <- 'AVNS_myNMlu7wBu69NOuFkU1'
db_name <- 'defaultdb'
db_host <- 'mysql-1c2ba4a8-northeastern-cee5.k.aivencloud.com'
db_port <- 19461

# 3. read data from db
mydb <- dbConnect(MySQL(), user = db_user, password = db_password, 
                  dbname = db_name, host = db_host, port = db_port)


# Create a simple test table
dbExecute(mydb, "CREATE TABLE test_table (id INT PRIMARY KEY, name VARCHAR(50));")

# Insert some data
dbExecute(mydb, "INSERT INTO test_table VALUES (1, 'Alice'), (2, 'Bob');")

# Query the data back
result <- dbGetQuery(mydb, "SELECT * FROM test_table;")
print(result)

# Clean up (optional)
dbExecute(mydb, "DROP TABLE test_table;")
```
```{r, echo = FALSE, message=FALSE, results='hide'}
dbDisconnect(conn)
dbDisconnect(con)
```
